import fs from 'node:fs';
import path from 'node:path';

export interface GenerateConfigOptions {
  /** Title shown in the Docusaurus navbar (default: "doc-slurp"). */
  siteTitle?: string;
  /** Production URL (default: "https://example.github.io"). */
  siteUrl?: string;
  /** Base path, e.g. "/doc-slurp/" (default: "/"). */
  baseUrl?: string;
  /** Location of the docs directory (default: "website/docs"). */
  docsDir?: string;
  /** Directory to write generated config files to (default: "website"). */
  outDir?: string;
}

/**
 * Discover repo directories and generate Docusaurus config + sidebar files.
 *
 * @returns The list of discovered repo names.
 */
export function generateSiteConfig(options: GenerateConfigOptions = {}): string[] {
  const siteTitle = options.siteTitle ?? 'doc-slurp';
  const siteUrl = options.siteUrl ?? 'https://example.github.io';
  const baseUrl = options.baseUrl ?? '/';
  const docsDir = options.docsDir ?? 'website/docs';
  const outDir = options.outDir ?? 'website';

  // Discover repos (top-level directories in docs output dir)
  const repos: string[] = [];
  if (fs.existsSync(docsDir)) {
    for (const entry of fs.readdirSync(docsDir, { withFileTypes: true })) {
      if (entry.isDirectory()) repos.push(entry.name);
    }
  }

  repos.sort();

  // ── Generate docusaurus.config.ts ──────────────────────────────────────────

  const configContent = `import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: ${JSON.stringify(siteTitle)},
  url: ${JSON.stringify(siteUrl)},
  baseUrl: ${JSON.stringify(baseUrl)},
  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',
  trailingSlash: false,

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          path: './docs',
          routeBasePath: '/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themes: [
    [
      '@easyops-cn/docusaurus-search-local',
      {
        hashed: true,
        indexDocs: true,
        docsRouteBasePath: '/',
        searchBarShortcutHint: false,
      },
    ],
  ],

  themeConfig: {
    navbar: {
      title: ${JSON.stringify(siteTitle)},
      items: [
        {
          type: 'doc',
          docId: ${repos.length > 0 ? JSON.stringify(`${repos[0]}/index`) : "'intro'"},
          position: 'left',
          label: 'Docs',
        },
      ],
    },
    footer: {
      style: 'dark',
      copyright: \`Built with doc-slurp · \${new Date().getFullYear()}\`,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
`;

  // ── Generate sidebars.ts ───────────────────────────────────────────────────

  const sidebarItems = repos.map(
    (repo) => `    {
      type: 'autogenerated',
      dirName: ${JSON.stringify(repo)},
    }`,
  );

  const sidebarsContent = `import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
${sidebarItems.join(',\n')}
  ],
};

export default sidebars;
`;

  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, 'docusaurus.config.ts'), configContent, 'utf-8');
  fs.writeFileSync(path.join(outDir, 'sidebars.ts'), sidebarsContent, 'utf-8');

  return repos;
}
