#!/usr/bin/env tsx
/**
 * scripts/generate-config.ts
 *
 * Generates website/docusaurus.config.ts and website/sidebars.ts based on the
 * directory structure under website/docs/ (one top-level folder per repo).
 *
 * Usage:
 *   npx tsx scripts/generate-config.ts
 *
 * Environment variables:
 *   SITE_TITLE      (optional) Title shown in the Docusaurus navbar (default: "doc-slurp").
 *   SITE_URL        (optional) Production URL (default: "https://example.github.io").
 *   BASE_URL        (optional) Base path, e.g. "/doc-slurp/" (default: "/").
 *   DOCS_OUT_DIR    (optional) Location of docs directory (default: "website/docs").
 */

import fs from 'node:fs';
import path from 'node:path';

const siteTitle = process.env['SITE_TITLE'] ?? 'doc-slurp';
const siteUrl = process.env['SITE_URL'] ?? 'https://example.github.io';
const baseUrl = process.env['BASE_URL'] ?? '/';
const docsOutDir = process.env['DOCS_OUT_DIR'] ?? 'website/docs';

// Discover repos (top-level directories in docs output dir)
const repos: string[] = [];
if (fs.existsSync(docsOutDir)) {
  for (const entry of fs.readdirSync(docsOutDir, { withFileTypes: true })) {
    if (entry.isDirectory()) repos.push(entry.name);
  }
}

repos.sort();

// ── Generate docusaurus.config.ts ──────────────────────────────────────────

const configContent = `import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: ${JSON.stringify(siteTitle)},
  url: ${JSON.stringify(siteUrl)},
  baseUrl: ${JSON.stringify(baseUrl)},
  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',
  trailingSlash: false,

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          path: './docs',
          routeBasePath: '/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themes: [
    [
      '@easyops-cn/docusaurus-search-local',
      {
        hashed: true,
        indexDocs: true,
        docsRouteBasePath: '/',
        searchBarShortcutHint: false,
      },
    ],
  ],

  themeConfig: {
    navbar: {
      title: ${JSON.stringify(siteTitle)},
      items: [
        {
          type: 'doc',
          docId: ${repos.length > 0 ? JSON.stringify(`${repos[0]}/index`) : "'intro'"},
          position: 'left',
          label: 'Docs',
        },
      ],
    },
    footer: {
      style: 'dark',
      copyright: \`Built with doc-slurp · \${new Date().getFullYear()}\`,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
`;

// ── Generate sidebars.ts ───────────────────────────────────────────────────

const sidebarItems = repos.map(
  (repo) => `    {
      type: 'autogenerated',
      dirName: ${JSON.stringify(repo)},
    }`,
);

const sidebarsContent = `import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
${sidebarItems.join(',\n')}
  ],
};

export default sidebars;
`;

fs.writeFileSync('website/docusaurus.config.ts', configContent, 'utf-8');
fs.writeFileSync('website/sidebars.ts', sidebarsContent, 'utf-8');

console.log(`Generated website/docusaurus.config.ts with ${repos.length} repos.`);
console.log('Generated website/sidebars.ts');
