import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { generateSiteConfig } from '../generate-config.js';

describe('generateSiteConfig', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'gen-config-test-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('generates config and sidebar files in the specified output directory', () => {
    const docsDir = path.join(tmpDir, 'docs');
    fs.mkdirSync(path.join(docsDir, 'repo-a'), { recursive: true });
    fs.mkdirSync(path.join(docsDir, 'repo-b'), { recursive: true });
    fs.writeFileSync(path.join(docsDir, 'repo-a', 'README.md'), '# A', 'utf-8');
    fs.writeFileSync(path.join(docsDir, 'repo-b', 'README.md'), '# B', 'utf-8');

    const outDir = path.join(tmpDir, 'out');
    const repos = generateSiteConfig({ docsDir, outDir });

    expect(repos).toEqual(['repo-a', 'repo-b']);
    expect(fs.existsSync(path.join(outDir, 'docusaurus.config.ts'))).toBe(true);
    expect(fs.existsSync(path.join(outDir, 'sidebars.ts'))).toBe(true);
  });

  it('uses custom site title, URL, and base URL', () => {
    const docsDir = path.join(tmpDir, 'docs');
    fs.mkdirSync(docsDir, { recursive: true });

    const outDir = path.join(tmpDir, 'out');
    generateSiteConfig({
      docsDir,
      outDir,
      siteTitle: 'My Docs',
      siteUrl: 'https://docs.example.com',
      baseUrl: '/docs/',
    });

    const config = fs.readFileSync(path.join(outDir, 'docusaurus.config.ts'), 'utf-8');
    expect(config).toContain('"My Docs"');
    expect(config).toContain('"https://docs.example.com"');
    expect(config).toContain('"/docs/"');
  });

  it('returns empty array when docs directory does not exist', () => {
    const outDir = path.join(tmpDir, 'out');
    const repos = generateSiteConfig({
      docsDir: path.join(tmpDir, 'nonexistent'),
      outDir,
    });

    expect(repos).toEqual([]);
    expect(fs.existsSync(path.join(outDir, 'docusaurus.config.ts'))).toBe(true);
  });

  it('sorts repo names alphabetically', () => {
    const docsDir = path.join(tmpDir, 'docs');
    fs.mkdirSync(path.join(docsDir, 'zebra'), { recursive: true });
    fs.mkdirSync(path.join(docsDir, 'alpha'), { recursive: true });
    fs.mkdirSync(path.join(docsDir, 'mid'), { recursive: true });

    const outDir = path.join(tmpDir, 'out');
    const repos = generateSiteConfig({ docsDir, outDir });

    expect(repos).toEqual(['alpha', 'mid', 'zebra']);
  });

  it('includes sidebar entries for each repo', () => {
    const docsDir = path.join(tmpDir, 'docs');
    fs.mkdirSync(path.join(docsDir, 'repo-x'), { recursive: true });
    fs.mkdirSync(path.join(docsDir, 'repo-y'), { recursive: true });

    const outDir = path.join(tmpDir, 'out');
    generateSiteConfig({ docsDir, outDir });

    const sidebars = fs.readFileSync(path.join(outDir, 'sidebars.ts'), 'utf-8');
    expect(sidebars).toContain('"repo-x"');
    expect(sidebars).toContain('"repo-y"');
    expect(sidebars).toContain('autogenerated');
  });
});
